# Generated by Django 4.2.5 on 2023-12-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='repositories_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queryhistory',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
